
POST http://127.0.0.1:8000/api/v1/token/
Content-Type: application/json

{"username": "user", "password": "user"}

###

GET http://127.0.0.1:8000/api/v1/follow/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIxODE5ODAyLCJqdGkiOiJkY2E1ZTZmYjQ4NDA0MWM4YThmOTRiNWM3MTMwZGIxYSIsInVzZXJfaWQiOjF9.Tkfw92C4w0SwTYtejjkFl7M1okMDXAQcMV0x8azMzPM

###
POST http://127.0.0.1:8000/api/v1/follow/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIxODIxODMwLCJqdGkiOiI1MTE4OWE4MWI3NjQ0ZDBkOTVmNmM2ZGQ5ZjcyY2EzMyIsInVzZXJfaWQiOjJ9.6alxNWadRz3ago_RxbZzFkbv3kJeM7n39RRi_jfdsnc

{
    "following": "admin"
}
