
POST http://127.0.0.1:8000/api/v1/token/
Content-Type: application/json

{"username": "user", "password": "user"}

###

GET http://127.0.0.1:8000/api/v1/follow/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIxODE5ODAyLCJqdGkiOiJkY2E1ZTZmYjQ4NDA0MWM4YThmOTRiNWM3MTMwZGIxYSIsInVzZXJfaWQiOjF9.Tkfw92C4w0SwTYtejjkFl7M1okMDXAQcMV0x8azMzPM

###
POST http://127.0.0.1:8000/api/v1/follow/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIxODIxODMwLCJqdGkiOiI1MTE4OWE4MWI3NjQ0ZDBkOTVmNmM2ZGQ5ZjcyY2EzMyIsInVzZXJfaWQiOjJ9.6alxNWadRz3ago_RxbZzFkbv3kJeM7n39RRi_jfdsnc

{
    "following": "admin"
}

ServerRunTests: 

```
./yatube_api/settings.py:107:2: W292 no newline at end of file
./api/serializers.py:2:1: F401 'rest_framework.validators.UniqueTogetherValidator' imported but unused
./api/views.py:7:80: E501 line too long (93 > 79 characters)
./api/views.py:37:80: E501 line too long (103 > 79 characters)
./api/views.py:48:1: W293 blank line contains whitespace
./api/views.py:49:13: E117 over-indented
./api/views.py:50:80: E501 line too long (99 > 79 characters)
./api/views.py:52:80: E501 line too long (89 > 79 characters)
./api/views.py:57:80: E501 line too long (82 > 79 characters)
./api/views.py:58:50: W291 trailing whitespace
./api/views.py:63:80: E501 line too long (98 > 79 characters)
./api/urls.py:2:1: F401 'rest_framework.authtoken.views' imported but unused
./api/urls.py:6:80: E501 line too long (91 > 79 characters)
./api/urls.py:17:80: E501 line too long (85 > 79 characters)
./api/urls.py:18:80: E501 line too long (91 > 79 characters)
./api/models.py:3:1: F401 'django.db.models.constraints.UniqueConstraint' imported but unused
./api/models.py:4:1: F401 'django.db.models.query_utils.Q' imported but unused
./api/models.py:91:1: W391 blank line at end of file
./api/permissions.py:19:42: W292 no newline at end of file
./api/tests.py:1:1: F401 'django.test.TestCase' imported but unused
================== Приведите код в соответствие с PEP8 ==================
```
